addpath(genpath('misc'));
addpath('filters_joint');
addpath('gen');
addpath('plot_functions');
addpath('results');
addpath('data_fusion');
addpath('run');
addpath('analyze_results');
addpath('track_matching');